/** Seeded per branch when the brand list is empty (first open of inventory or setup). */
export const DEFAULT_INVENTORY_BRANDS = [
  "Carrier",
  "Condura",
  "Daikin",
  "Fujitsu",
  "Gree",
  "Haier",
  "Hisense",
  "Hitachi",
  "Koppel",
  "LG",
  "Midea",
  "Mitsubishi Electric",
  "Mitsubishi Heavy",
  "Panasonic",
  "Samsung",
  "Sharp",
  "TCL",
  "Toshiba",
  "Trane",
  "York",
  "Other / generic",
];
